baseURL = "https://sp4ee.github.io/"
title = "Solarpunk Forever Engine"
disableKinds = ["RSS","taxonomy","taxonomyTerm"]
contentdir = "content"
layoutdir =  "layouts"
staticdir =  "static"
publishdir = "public"
enableRobotsTXT = "true"
  
[params]
  homeMotto = "A sustainable and symbiotic intelligent machine"

[permalinks]
  page = "/:filename/"

[outputs]
home = ["HTML"]
